### ISSUE TITLE
ImageToVTKImageFilter does not work

### ISSUE THREAD

**Issue by hellowangqian** [InsightSoftwareConsortium/ITKVtkGlue#23]
Using pip install itk-vtkglue
Tried with both python2 and python3, the following line kills the process:
itkToVtkFilter = itk.ImageToVTKImageFilter.New()

**Comment by thewtex** [comment]
We will be addressing this after the ITK 5.0.0 release.

CC: @fbudin69500

**Comment by hellowangqian** [comment]
Glad to hear that, thank you!
