### ISSUE TITLE
Unknown CMake command "itk_module_add_library".

### ISSUE THREAD

**Issue by EmileSonneveld** [InsightSoftwareConsortium/ITKVtkGlue#32]
I try to glue together ITK4.10 and VTK from 9f8ec53e651644e9352e00f564adc5f4ffe3eab9.
When I configure the project with Cmake (3.15.3) I get the following error:
> Unknown CMake command "itk_module_add_library".
![image](https://user-images.githubusercontent.com/2298426/71576598-677dbd00-2af1-11ea-8492-ec8888bcf531.png)

Is there something I am missing out? Doesn't ITKVtkGlue work with older versions?

**Comment by thewtex** [comment]
This module is only intended to work with the latest version of ITK.
