### ISSUE TITLE
Building ITKVtkGlue runs into ITKModuleExternal not found

### ISSUE THREAD

**Issue by hyz9181** [InsightSoftwareConsortium/ITKVtkGlue#40]
Hi!

I am trying to build ITKVtkGlue from scratch but I am running into error. When I run the `setup.py` by building the ITKVtkGlue, it runs into CMake error shows that:

`CMake Error at CMakeLists.txt:205 (include):
  include could not find requested file:
    ITKModuleExternal
`

I have built ITK with C++ version 5.3.0 and my operating system is Ubuntu 22.04.3 LTS. 
How to solve this?

**Comment by phcerdan** [comment]
This is an external module to ITK, you need to enable it inside ITK or build it pointing to a current ITK build.
